---
title: "Linear_regressions"
author: "Andreas"
date: "10/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# BARSEL04 - modeller for far og mors gennemsnitlig antal barselsdage efter uddannelse, landsdel, år og interaktion på landsdel og udd. 

```{r}
barsel04_big <- read_rds("Data/barsel04.rds")
unique(barsel04_big$UDDKOMB)
```


## Far data
```{r}
barsel04_far <- barsel04_big %>% filter(TAL %in% "Far - barselsdagpengedage i gennemsnit", 
                                        ORLOV1 %in% "Alle forældrepar, uanset deling af orlov",
                                        grepl(UDDKOMB, pattern = "Far"), #uddannelseskombinationer som kun indeholder far
                                        grepl("Landsdel", OMRÅDE)) %>% 
                                select(UDDKOMB, OMRÅDE, TID, INDHOLD) %>% 
                                arrange(OMRÅDE, TID) %>% 
                                mutate(INDHOLD = parse_number(INDHOLD, locale = locale(decimal_mark = ",")),
                                       TID = factor(TID))
barsel04_far
```

### Far model
```{r}
LM_interaction_far <- lm(data = barsel04_far, INDHOLD ~ UDDKOMB + OMRÅDE + TID + UDDKOMB*OMRÅDE) 
summary(LM_interaction_far)

LM_no_interaction_far <- lm(data = barsel04_far, INDHOLD ~ UDDKOMB + OMRÅDE + TID)
summary(LM_no_interaction_far)

#test for reduktion til model uden interaktion:
anova(LM_interaction_far, LM_no_interaction_far)
```


## Mor data
```{r}
uddannelser_mor <- unique(barsel04_big$UDDKOMB)[2:6] #Mor har hhv. Ingen ungdomsudd., ungdomsudd, KVU, MVU, LVU

barsel04_mor <- barsel04_big %>% filter(TAL %in% "Mor - barselsdagpengedage i gennemsnit", 
                                        ORLOV1 %in% "Alle forældrepar, uanset deling af orlov",
                                        UDDKOMB %in% uddannelser_mor, #uddannelseskombinationer som kun indeholder far
                                        grepl("Landsdel", OMRÅDE)) %>% 
                                select(UDDKOMB, OMRÅDE, TID, INDHOLD) %>% arrange(OMRÅDE, TID) %>% 
                                mutate(INDHOLD = parse_number(INDHOLD, locale = locale(decimal_mark = ",")),
                                       TID = factor(TID))
barsel04_mor
```


### Mor model

```{r}
LM_interaction_mor <- lm(data = barsel04_mor, INDHOLD ~ UDDKOMB + OMRÅDE + TID + UDDKOMB*OMRÅDE) 
summary(LM_interaction_mor)

LM_no_interaction_mor <- lm(data = barsel04_mor, INDHOLD ~ UDDKOMB + OMRÅDE + TID)
summary(LM_no_interaction_mor)

#test for reduktion til model uden interaktion:
anova(LM_interaction_mor, LM_no_interaction_mor)
```

