---
title: "Plots"
author: "Clara Wolff Jespersen"
date: "11/03/2022"
output: html_document
theme: readable
---


```{r}
library(tidyverse)
library(statsDK)
library(readxl)
```



```{r}

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

scale_fill_manual(values=cbbPalette)
  
df <- read_rds(file = "Data/barsel04.rds")

df$value <- str_replace_all(df$INDHOLD, pattern = ",", replacement = ".") %>% as.double()

pd <- df %>% 
      filter(TAL %in% "Far - barselsdagpengedage i gennemsnit", 
            ORLOV1 %in% "Alle forældrepar, uanset deling af orlov",
                                        grepl(UDDKOMB, pattern = "Far"), #uddannelseskombinationer som kun indeholder far
                                        OMRÅDE %in% c("Landsdel Nordsjælland","Landsdel Vestjylland")) %>% 
                                        select(UDDKOMB, OMRÅDE, TID, INDHOLD) %>% 
                                        arrange(OMRÅDE, TID) %>% 
                                        mutate(INDHOLD = parse_number(INDHOLD, locale = locale(decimal_mark = ",")),
                                        TID = factor(TID))


pd <- pd %>% mutate(UDDKOMB=fct_inorder(UDDKOMB))


pd %>% mutate(OMRÅDE=fct_relevel(OMRÅDE,"Landsdel Vestjylland","Landsdel Nordsjælland")) %>% 
  filter(TID=="2019") %>% 
  ggplot(aes(x=UDDKOMB, y=INDHOLD, fill=OMRÅDE)) +
  geom_col(position = position_dodge2()) +
  scale_fill_manual(values=cbbPalette[c(3,8)])+
  ylab("Gns. #Barselsdage for fædre")+
  xlab("Fars uddannelsesniveau")+
  scale_x_discrete(" Fars Uddannelsesniveau",
    labels = c(
      "Far har ingen ungdomsuddannelse" = "Ingen ungdomsuddannelse",
      "Far har ungdomsuddannelse." = "Ungdomsuddannelse",
      "Far har Kort videregående uddannelse (KVU)" = "Kort videregående",
      "Far har Mellemlang videregående uddannelse (MVU)" = "Mellemlang videregående",
      "Far har Lang videregående uddannelse (LVU)" = "Lang videregående"
    ))+
  scale_fill_manual(values=c("skyblue2","palegreen2"),name="Landsdel")+
  theme_classic()+
  theme(text = element_text(size = 8))+
  coord_flip()
```

```{r}
pd$OMRÅDE[pd$INDHOLD==max(pd$INDHOLD[pd$UDDKOMB=="Far har Lang videregående uddannelse (LVU)"])]
pd$OMRÅDE[pd$INDHOLD==min(pd$INDHOLD[pd$UDDKOMB=="Far har Lang videregående uddannelse (LVU)"])]
```
```{r}
all<- df %>% 
      filter(TAL %in% "Far - barselsdagpengedage i gennemsnit", 
            ORLOV1 %in% "Alle forældrepar, uanset deling af orlov",
                                        grepl(UDDKOMB, pattern = "Far")) %>%  #uddannelseskombinationer som kun indeholder far 
                                        filter(OMRÅDE=="Hele landet") %>% 
                                        select(UDDKOMB, OMRÅDE, TID, INDHOLD) %>% 
                                        arrange(OMRÅDE, TID) %>% 
                                        mutate(INDHOLD = parse_number(INDHOLD, locale = locale(decimal_mark = ",")),
                                        TID = factor(TID))


all <- all %>% mutate(UDDKOMB=fct_inorder(UDDKOMB))



all %>% 
  ggplot(aes(x=UDDKOMB, y=INDHOLD, col=TID)) +
  geom_point() +
  geom_line(aes(group=TID))+
  ylab("Gns. antal barselsdage for fædre")+
  xlab("Fars uddannelsesniveau")+
  scale_x_discrete("Uddannelsesniveau",
    labels = c(
      "Far har ingen ungdomsuddannelse" = "Ingen ungdomsuddannelse",
      "Far har ungdomsuddannelse." = "Ungdomsuddannelse",
      "Far har Kort videregående uddannelse (KVU)" = "Kort videregående",
      "Far har Mellemlang videregående uddannelse (MVU)" = "Mellemlang videregående",
      "Far har Lang videregående uddannelse (LVU)" = "Lang videregående"
    )
    ,guide = guide_axis(n.dodge = 2))+
  theme_classic()+
  geom_hline(yintercept=c(20,30,40,50),color="grey",size=0.1)+
  theme(text = element_text(size = 8))

```

```{r}
ford<-read_excel(path="Data/Fordelingbrancher.xlsx")
```

```{r}
ford<-ford %>% pivot_wider(names_from = ERHVERV,values_from=`2019`) %>% 
group_by(OMRÅDE) %>%
mutate_at(vars("A Landbrug, skovbrug og fiskeri":"X Uoplyst aktivitet"), funs(./`TOT Erhverv i alt`))
```

```{r}
ford_branche<-ford %>% select(!"TOT Erhverv i alt") %>% pivot_longer(!OMRÅDE,names_to="Branche",values_to="Andel i branche")
```




```{r}

ford_branche %>% filter(OMRÅDE %in% c("Landsdel Nordsjælland","Landsdel Vestjylland")) %>%  
  mutate(OMRÅDE=fct_relevel(OMRÅDE,"Landsdel Vestjylland","Landsdel Nordsjælland")) %>% 
   mutate(Branche=fct_relevel(Branche,"CA Føde-, drikke- og tobaksvareindustri","A Landbrug, skovbrug og fiskeri","CK Maskinindustri","MA Rådgivning mv.","JC It- og informationstjenester","K Finansiering og forsikring","CI Elektronikindustri")) %>% 
  filter(Branche %in% c("MA Rådgivning mv.","K Finansiering og forsikring","JC It- og informationstjenester","CK Maskinindustri","CA Føde-, drikke- og tobaksvareindustri","A Landbrug, skovbrug og fiskeri","CI Elektronikindustri")) %>% 
  ggplot(aes(x=Branche, y=`Andel i branche`, fill=OMRÅDE)) +
  geom_col(position = position_dodge(),width = 0.8) +
  scale_fill_manual(values=c("skyblue2","palegreen2"),name="Landsdel")+
  ylab("Andel")+
  xlab("Brancher")+
  theme_classic()+
  theme(text = element_text(size = 8))+
  coord_flip()
```



```{r}
udd_landsdele_2019 <- read_excel(path='Data/uddannelsesgrupper_landsdele_2019.xlsx')

udd_landsdele_2019 <- cbind(udd_landsdele_2019, Antal_indbyggere = rowSums(udd_landsdele_2019[,2:11]))
```


```{r}
udd_landsdele_2019 <- udd_landsdele_2019 %>% mutate(Ingen_ungdomsuddannelse=`H10 Grundskole`, Ungdomsuddannelse=`H20 Gymnasiale uddannelser`+`H30 Erhvervsfaglige uddannelser`+`H35 Adgangsgivende uddannelsesforløb`, Kort_videregående=`H40 Korte videregående uddannelser, KVU`, Mellemlang_videregående = `H50 Mellemlange videregående uddannelser, MVU` + `H60 Bacheloruddannelser, BACH`, Lang_videregående=`H70 Lange videregående uddannelser, LVU` + `H80 Ph.d. og forskeruddannelser`, Uoplyst=`H90 Uoplyst mv.`)

udd_landsdele_2019 <- udd_landsdele_2019 %>% select(Landsdel, Ingen_ungdomsuddannelse, Ungdomsuddannelse, Kort_videregående, Mellemlang_videregående, Lang_videregående, Uoplyst, Antal_indbyggere)
```

```{r}
udd_landsdele_prop_2019 <- udd_landsdele_2019 %>% mutate(ProportionIngen=Ingen_ungdomsuddannelse/Antal_indbyggere, ProportionUngdoms=Ungdomsuddannelse/Antal_indbyggere, ProportionKort=Kort_videregående/Antal_indbyggere, ProportionMellem= Mellemlang_videregående/Antal_indbyggere, ProportionLang=Lang_videregående/Antal_indbyggere, ProportionUoplyst=Uoplyst/Antal_indbyggere) %>% select(Landsdel, ProportionIngen, ProportionUngdoms, ProportionKort, ProportionMellem, ProportionLang, ProportionUoplyst)
```

```{r}
udd_pivot <- udd_landsdele_prop_2019  %>% rename(Uoplyst=ProportionUoplyst, Ungdomsuddannelse=ProportionUngdoms, KortVidere=ProportionKort, MellemLang=ProportionMellem, Lang = ProportionLang, Ingen=ProportionIngen) %>% pivot_longer(!Landsdel, names_to = "Uddannelse", values_to = "Proportion")

udd_pivot <- udd_pivot %>% mutate(Uddannelse=fct_inorder(Uddannelse))

udd_pivot %>% filter(Landsdel %in% c("Landsdel Nordsjælland","Landsdel Vestjylland")) %>%  
  mutate(Landsdel=fct_relevel(Landsdel,"Landsdel Vestjylland","Landsdel Nordsjælland")) %>% 
  filter(Uddannelse!="Uoplyst") %>% 
  ggplot(aes(x=Uddannelse, y=Proportion, fill=Landsdel)) +
  geom_col(position = position_dodge(),width = 0.8) +
  scale_fill_manual(values=c("skyblue2","palegreen2"))+
  ylab("Andel")+
  xlab("Uddannelse")+
  scale_x_discrete("Uddannelsesniveau",
    labels = c(
      "Ingen" = "Ingen ungdomsuddannelse",
      "Ungdomsuddannelse." = "Ungdomsuddannelse",
      "KortVidere" = "Kort videregående",
      "MellemLang" = "Mellemlang videregående",
      "Lang" = "Lang videregående"
    ))+
  theme_classic()+
  theme(text = element_text(size = 8))+
  coord_flip()
```

Taget fra IFOR22 (Christiansø mangler, men er undtaget fra gennemsnittet, da det alligevel er en meget lille kommune)
```{r}
deciler_kommuner <- read_excel("Data/deciler_kommuner_2019.xlsx")

kommune_landsdel_udenchristian <- kommune_landsdel %>% filter(Kommune!='Christiansø')

deciler_landsdel_2019 <- deciler_kommuner %>% full_join(kommune_landsdel_udenchristian) %>% group_by(Landsdel) %>% summarise(Q10=mean(`1. decil`), Q50=mean(`5. decil`),Q90=mean(`9. decil`), Antal_kommuner=n())

deciler_landsdel_2019
```

```{r}
### ulighed for vestjylland og nordsjælland
folketal_kommuner <- read_excel("Data/Kommune_folketal_2019.xlsx")
folketal_kommuner <- folketal_kommuner %>% filter(Kommune!='Christiansø')

kommune_landsdel_udenchristian <- kommune_landsdel %>% filter(Kommune!='Christiansø')
```

```{r}
deciler_landsdel_2019_nordvest <- deciler_kommuner %>% full_join(kommune_landsdel_udenchristian) %>% group_by(Landsdel) %>% filter(Landsdel %in% c("Landsdel Nordsjælland","Landsdel Vestjylland")) %>% full_join(folketal_kommuner) 

landsdel_folketal <- deciler_landsdel_2019_nordvest %>% group_by(Landsdel) %>% summarise(SamletAntal=sum(Antal), n=n())

deciler_landsdel_2019_nordvest <- deciler_landsdel_2019_nordvest %>% full_join(landsdel_folketal) %>% select(!n) %>% mutate(prop=Antal/SamletAntal) %>% group_by(Landsdel) %>% summarise(Q10=sum(prop*`1. decil`),Q90=sum(prop*`9. decil`),Antal_kommuner=n())
```

```{r}
deciler_landsdel_2019_nordvest <- deciler_landsdel_2019_nordvest %>% mutate(ulighed=Q90/Q10)

deciler_landsdel_2019_nordvest
```


```{r}
folketal_kommuner <- read_excel("Data/Kommune_folketal_2019.xlsx")
folketal_kommuner <- folketal_kommuner %>% filter(Kommune!='Christiansø')

deciler_landsdel_2019_helelandet <- deciler_kommuner %>% full_join(folketal_kommuner) %>% mutate(Land="Danmark")
deciler_landsdel_2019_helelandet

land_folketal <- deciler_landsdel_2019_helelandet %>% group_by(Land) %>% summarise(SamletAntal=sum(Antal), n=n())
land_folketal

deciler_landsdel_2019_helelandet <- deciler_landsdel_2019_helelandet %>% full_join(land_folketal) %>% select(!n) %>%  mutate(prop=Antal/SamletAntal) %>% group_by(Land) %>% summarise(Q10=sum(prop*`1. decil`),Q90=sum(prop*`9. decil`),Antal_kommuner=n())
deciler_landsdel_2019_helelandet

deciler_landsdel_2019_helelandet <- deciler_landsdel_2019_helelandet %>% mutate(ulighed=Q90/Q10) 
deciler_landsdel_2019_helelandet
```

```{r}
deciler_landsdel_2019_nordvest%>% mutate(Landsdel=fct_relevel(Landsdel,"Landsdel Nordsjælland","Landsdel Vestjylland")) %>% 
  filter(Landsdel %in% c("Landsdel Nordsjælland","Landsdel Vestjylland")) %>% 
  ggplot(aes(x=Landsdel, y=ulighed, fill=Landsdel)) +
  geom_col(position = position_dodge2()) +
  scale_fill_manual(values=cbbPalette[c(3,8)])+
  ylab("Ulighed")+
  xlab("Landsdel")+
  scale_fill_manual(values=c("skyblue2","palegreen2"),name="Landsdel")+
  theme_classic()+
  geom_hline(aes(yintercept=3.212436),color="red")+
  theme(text = element_text(size = 8))+
  coord_flip()
```

